#!/bin/bash
# Checks wi-fi signal strength and prints information accordingly

STRENGTH=`grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70)}'`
echo $STRENGTH

if ((0<=STRENGTH && STRENGTH<=40))
then
    echo "case1"
elif ((40<STRENGTH && STRENGTH<=60))
then
    echo "case2"
elif ((60<STRENGTH && STRENGTH<=80))
then
    echo "case3"
else
    echo ""
fi


