#!/bin/bash

SCRIPT_FOLDER="$HOME/.scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
  echo File already exists!
else
  echo '#!/bin/bash' > $SCRIPT_FILE
  chmod +x $SCRIPT_FILE
  $EDITOR $SCRIPT_FILE
fi

