#!/bin/bash

WALLPAPER_FOLDER="$HOME/.config/"
EXTENSION="${1##*.}"

find $WALLPAPER_FOLDER -name "wallpaper.*" -exec rm -r {} \;

cp $1 $WALLPAPER_FOLDER/wallpaper.$EXTENSION

feh --bg-scale $WALLPAPER_FOLDER/wallpaper.$EXTENSION

